routes/web.php
    Route::resource('administration/deposits', 'Administration\DepositsController');
    Route::post('/administration/deposits/{deposits}/restore', 'Administration\DepositsController@restoreTrashed')->name('deposits.restore');
    Route::get('/datatable/administration/deposits', 'Administration\DepositsController@dataTable');


    /** Seguros de mala práxis */
    Route::resource('administration/medicalMalpracticeInsurances', 'Administration\MedicalMalpracticeInsurances');
    Route::get('/datatable/administration/medicalMalpracticeInsurances', 'Administration\MedicalMalpracticeInsurances@dataTable');

    /**Especialistas */

    Route::resource('administration/specialists', 'Administration\SpecialistsController');
    Route::get('/datatable/administration/specialists', 'Administration\SpecialistsController@dataTable');


    /**
     * Rangos de prácticas de nomencladores
     */
    Route::resource('administration/nomenclatorRanges', 'Administration\NomenclatorRanges');
    Route::get('/datatable/administration/nomenclatorRanges', 'Administration\NomenclatorRanges@dataTable');

    /**Grupos de Practicas de Nomencladores */

    Route::resource('administration/nomenclatorPracticesGroup', 'Administration\NomenclatorPracticesGroupController');
    Route::get('/datatable/administration/nomenclatorPracticesGroup', 'Administration\NomenclatorPracticesGroupController@dataTable');

    /**
     * Convenios con obras sociales
     */
    /*RESOURCE*/
    Route::resource('billingDepartment/medicalInsuranceAgreements', 'BillingDepartment\MedicalInsuranceAgreements');
    /*DataTable de convenios*/
    Route::get('/datatable/billingDepartment/medicalInsuranceAgreements', 'BillingDepartment\MedicalInsuranceAgreements@dataTable');
    /*Modal para importar archivo de excel con las practicas valorizadas*/
    Route::get('/modals/billingDepartment/practicesAgreementModal/{medicalInsuranceAgreementId}', 'BillingDepartment\MedicalInsuranceAgreements@practicesAgreementModal');
    /*POST para subir archivo de practicas valorizadas*/
    Route::post('/billingDepartment/uploadPracticesAgreement/{medicalInsuranceAgreementId}', 'BillingDepartment\MedicalInsuranceAgreements@uploadPracticesAgreement')->name('medicalInsuranceAgreement.uploadPractices');
    /*DataTable de practicas convenidas*/
    Route::get('/datatable/billingDepartment/medicalInsurancePracticesAgreement/{medicalInsuranceAgreementId}', 'BillingDepartment\MedicalInsuranceAgreements@practicesAgreementDataTable');
    /*Vista de practicas convenidas*/
    Route::get('/billingDepartment/practicesAgreement/{medicalInsuranceAgreementId}', 'BillingDepartment\MedicalInsuranceAgreements@practicesAgreement');

    /*Modal para agregar una pràctica al convenio manualmente*/
    Route::get('/modals/billingDepartment/addPracticeAgreementModal', 'BillingDepartment\MedicalInsuranceAgreements@addPracticeAgreementModal');
    Route::post('/billingDepartment/practicesAgreement/{medicalInsuranceAgreementId}', 'BillingDepartment\MedicalInsuranceAgreements@storePracticeAgreement');
    /*Eliminar una pràctica convenida*/
    Route::post('/billingDepartment/practicesAgreement/{medicalInsuranceAgreementId}/delete', 'BillingDepartment\MedicalInsuranceAgreements@deleteSinglePracticeAgreement');

    /**
     * Categorías de empleados
     */
    Route::resource('/humanResourcesDepartment/employeesCategories', 'HumanResourcesDepartment\EmployeesCategories');
    Route::get('/datatable/humanResourcesDepartment/employeesCategories', 'HumanResourcesDepartment\EmployeesCategories@dataTable');

    /**
     * Pacientes
     */
    Route::resource('administration/patients', 'Administration\PatientsController');
    Route::get('/datatable/administration/patients', 'Administration\PatientsController@dataTable');
    Route::get('/administration/patient/findByDocumentNumber/{documentTypeId}/{documentNumber}', 'Administration\PatientsController@findByDocumentNumber');
    Route::get('/administration/patient/patientMedicalInsurances/{documentTypeId}/{documentNumber}', 'Administration\PatientsController@getPatientMedicalInsurances');

    /**
     * Helpers
     **/
    //Ciudades
    Route::get('/helpers/cities/cityByProvinceId/{provinceId}', 'HelpersController@citiesByProvinceId');
    //Rendiciones abiertas
    Route::get('/helpers/getOpenedCheckingAccounts/{documentTypeId}/{documentNumber}', 'HelpersController@getOpenedCheckingAccounts');

    /**
     * Farmacia
     */
    Route::resource('pharmacy/medicaments', 'Pharmacy\MedicamentsController');
    Route::get('pharmacy/medicamentsUpdate', 'Pharmacy\MedicamentsController@medicamentsUpdate');
    Route::post('pharmacy/medicamentsUpdate', 'Pharmacy\MedicamentsController@uploadAlphaBetaZipFile');
    Route::get('/datatable/pharmacy/medicaments', 'Pharmacy\MedicamentsController@dataTable');
    Route::get('/datatable/pharmacy/medicamentUpdates', 'Pharmacy\MedicamentsController@medicamentUpdatesDataTable');


    /*Rendiciones*/
    Route::get('/billingDepartment/patientCheckingAccounts', 'PatientCheckingAccounts\PatientCheckingAccounts@index');
    Route::get('/datatable/billingDepartment/patientCheckingAccounts', 'PatientCheckingAccounts\PatientCheckingAccounts@dataTable');

    /*Check in de pacientes*/
    /*Ambulatorios*/
    Route::get('/patientCheckingAccounts/ambulatory/checkIn', 'PatientCheckingAccounts\Ambulatory\AmbulatoryPatientsCheckingAccount@checkIn');
    Route::post('/patientCheckingAccounts/ambulatory/checkIn', 'PatientCheckingAccounts\Ambulatory\AmbulatoryPatientsCheckingAccount@storeNewCheckingAccount');
    Route::get('/patientCheckingAccounts/ambulatory/finalStepInformation/{documentTypeId}/{documentNumber}/{medicalInsuranceId}', 'PatientCheckingAccounts\Ambulatory\AmbulatoryPatientsCheckingAccount@getAmbulatoryCheckingAccountFinalStepInformation');

    /*Departamentos Medicos*/


    Route::prefix('medicalDepartments')->group(function() {

        /*Anatomía patológica*/
        Route::get('/pathologicalAnatomy', 'MedicalDepartments\PathologicalAnatomy\PathologicalAnatomyController@index'); //Indice de muestras
        Route::get('/pathologicalAnatomy/create', 'MedicalDepartments\PathologicalAnatomy\PathologicalAnatomyController@create'); //Crear muestra
        Route::post('/pathologicalAnatomy/create', 'MedicalDepartments\PathologicalAnatomy\PathologicalAnatomyController@store'); //Crear muestra
        Route::delete('/pathologicalAnatomy/{id}/delete', 'MedicalDepartments\PathologicalAnatomy\PathologicalAnatomyController@destroy')->name('pathologicalAnatomyStudy.destroy'); //Eliminar muestra
        Route::get('/datatable/PathologicalAnatomy', 'MedicalDepartments\PathologicalAnatomy\PathologicalAnatomyController@dataTable'); //Tabla de muestras
        Route::get('/pathologicalAnatomy/printSticker/{studyCode}', 'MedicalDepartments\PathologicalAnatomy\PathologicalAnatomyController@printSticker');

        /*Reporte medico anatomía patológica*/
        Route::get('/datatable/PathologicalAnatomy/medicalReport', 'MedicalDepartments\PathologicalAnatomy\PathologicalAnatomyController@dataTableForMedicalReport'); //Tabla de muestras para crear reporte medico
        Route::get('/pathologicalAnatomy/medicalReport', 'MedicalDepartments\PathologicalAnatomy\PathologicalAnatomyController@medicalReport'); //Indice de muestras para crear reporte medico
        Route::get('/pathologicalAnatomy/billingCodesAssignment/{sampleId}', 'MedicalDepartments\PathologicalAnatomy\PathologicalAnatomyController@billingCodesAssignment'); //Asignar codigos de facturacion a muestras
        Route::post('/pathologicalAnatomy/billingCodesAssignment/{sampleId}', 'MedicalDepartments\PathologicalAnatomy\PathologicalAnatomyController@syncBillingCodesWithSample'); //Asignar codigos de facturacion a muestras
        Route::get('/pathologicalAnatomy/categorizeSample/{sampleId}', 'MedicalDepartments\PathologicalAnatomy\PathologicalAnatomyController@categorizeSample'); //Categorizar la muestra
        Route::post('/pathologicalAnatomy/categorizeSample/{sampleId}', 'MedicalDepartments\PathologicalAnatomy\PathologicalAnatomyController@syncCategoriesWithSample'); //Categorizar la muestra
        Route::get('/pathologicalAnatomy/{sampleId}/writeMedicalReport', 'MedicalDepartments\PathologicalAnatomy\PathologicalAnatomyController@writeMedicalReport');
        Route::post('/pathologicalAnatomy/{sampleId}/writeMedicalReport', 'MedicalDepartments\PathologicalAnatomy\PathologicalAnatomyController@storeMedicalReport');
        Route::get('/pathologicalAnatomy/medicalReportTemplates/getTitle/{titleId}', 'MedicalDepartments\PathologicalAnatomy\PathologicalAnatomyController@getMedicalReportTitle');
        Route::get('/pathologicalAnatomy/medicalReportTemplates/getTemplatesByCategory/{templateCategoryId}', 'MedicalDepartments\PathologicalAnatomy\PathologicalAnatomyController@getTemplatesByCategory');
        Route::get('/pathologicalAnatomy/medicalReportTemplates/getTemplate/{templateId}', 'MedicalDepartments\PathologicalAnatomy\PathologicalAnatomyController@getMedicalReportTemplate');
        Route::get('/pathologicalAnatomy/PapanicolaouTemplateDialog', 'MedicalDepartments\PathologicalAnatomy\PathologicalAnatomyController@papanicolaouTemplateDialog');
        Route::get('/pathologicalAnatomy/getPapanicolaouTemplateDescription/{templateId}', 'MedicalDepartments\PathologicalAnatomy\PathologicalAnatomyController@getPapanicolaouTemplateDescription');

        /*Categorías de estudios"*/
        Route::get('/pathologicalAnatomy/categories/levelOne/childCategories/{CategoryId}', 'MedicalDepartments\PathologicalAnatomy\PathologicalAnatomyLevelOneCategories@childCategories');
        Route::get('/pathologicalAnatomy/categories/levelTwo/childCategories/{CategoryId}', 'MedicalDepartments\PathologicalAnatomy\PathologicalAnatomyLevelTwoCategories@childCategories');

app/Models/Pharmacy/Medicament.php
<?php

namespace CloudMed\Models\Pharmacy;

use Illuminate\Database\Eloquent\Model;

class Medicament extends Model
{
    public $table = 'medicaments';

    protected $fillable = [
        'label',
        'name',
        'presentation',
        'laboratory_name',
        'cost_price',
        'sell_price',
        'laboratory_code',
        'alphabeta_medicament_id',
        'is_active',
        'barcode',
        'units',
        'medicament_drug_code',
        'medicament_pharmacological_action_code',
        'medicament_administration_line_code',
        'medicament_category_id',
        'on_stock'
    ];

    protected $casts = [
        'label' => 'string',
        'name' => 'string',
        'presentation' => 'string',
        'laboratory_name' => 'string',
        'cost_price' => 'double',
        'sell_price' => 'double',
        'laboratory_code' => 'integer',
        'alphabeta_medicament_id' => 'integer',
        'is_active' => 'boolean',
        'barcode' => 'string',
        'units' => 'integer',
        'medicament_drug_code' => 'integer',
        'medicament_pharmacological_action_code' => 'integer',
        'medicament_administration_line_code' => 'integer',
        'medicament_category_id' => 'integer'
    ];

    public function pharmacologicalAction()
    {
        return $this->belongsTo(MedicamentPharmacologicalAction::class, 'medicament_pharmacological_action_code', 'code');
    }

    public function drug()
    {
        return $this->belongsTo(MedicamentDrug::class, 'medicament_drug_code', 'code');
    }

    public function administrationLine()
    {
        return $this->belongsTo(MedicamentAdministrationLine::class, 'medicament_administration_line_code', 'code');
    }

    public function laboratory()
    {
        return $this->belongsTo(PharmaceuticalLaboratory::class, 'laboratory_code', 'code');
    }

    public function category()
    {
        return $this->belongsTo(MedicamentCategory::class, 'medicament_category_id');
    }
}

app/Models/Pharmacy/MedicamentAdministrationLine.php
<?php

namespace CloudMed\Models\Pharmacy;

use Illuminate\Database\Eloquent\Model;

class MedicamentAdministrationLine extends Model
{
    public $table = 'medicament_administration_lines';

    protected $fillable = ['code', 'description'];

    protected $casts = [
      'id' => 'integer',
      'code' => 'integer',
      'description' => 'string',
    ];
}

app/Models/Pharmacy/MedicamentCategory.php
<?php

namespace CloudMed\Models\Pharmacy;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Wildside\Userstamps\Userstamps;

class MedicamentCategory extends Model
{
    use SoftDeletes;
    use Userstamps;

    public $table = 'medicament_categories';

    protected $fillable = ['description'];

    protected $casts = [
        'id' => 'integer',
        'description' => 'string'
    ];
}

app/Models/Pharmacy/MedicamentDrug.php
<?php

namespace CloudMed\Models\Pharmacy;

use Illuminate\Database\Eloquent\Model;

class MedicamentDrug extends Model
{
    public $table = 'medicament_drugs';

    protected $fillable = ['code', 'description'];

    protected $casts = [
        'id' => 'integer',
        'code' => 'integer',
        'description' => 'string',
    ];
}

app/Models/Pharmacy/MedicamentPharmacologicalAction.php
<?php

namespace CloudMed\Models\Pharmacy;

use Illuminate\Database\Eloquent\Model;

class MedicamentPharmacologicalAction extends Model
{
    public $table = 'medicament_pharmacological_actions';

    protected $fillable = ['code', 'description'];

    protected $casts = [
        'id' => 'integer',
        'code' => 'integer',
        'description' => 'string',
    ];
}

app/Models/Pharmacy/MedicamentUpdateQueue.php
<?php

namespace CloudMed\Models\Pharmacy;

use CloudMed\User;
use Illuminate\Database\Eloquent\Model;

class MedicamentUpdateQueue extends Model
{
    public $table = 'medicament_updates_queue';

    protected $fillable = ['user_id', 'medicament_update_status_id'];

    protected $casts = [
        'id' => 'integer',
        'user_id' => 'integer',
        'medicament_update_status_id' => 'integer',
    ];

    public function status()
    {
        return $this->belongsTo(MedicamentUpdateStatus::class, 'medicament_update_status_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}

app/Models/Pharmacy/MedicamentUpdateStatus.php
<?php

namespace CloudMed\Models\Pharmacy;

use Illuminate\Database\Eloquent\Model;

class MedicamentUpdateStatus extends Model
{
    public $table = 'medicament_update_statuses';

    protected $fillable = ['name'];

    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
    ];
}

app/Models/Pharmacy/PharmaceuticalLaboratory.php
<?php

namespace CloudMed\Models\Pharmacy;

use Illuminate\Database\Eloquent\Model;

class PharmaceuticalLaboratory extends Model
{
    public $table = 'pharmaceutical_laboratories';

    protected $fillable = ['code', 'name'];

    protected $casts = [
        'id' => 'integer',
        'code' => 'integer',
        'name' => 'string',
    ];
}

app/Http/Controllers/Pharmacy/MedicamentsController.php
<?php

namespace CloudMed\Http\Controllers\Pharmacy;

use CloudMed\Http\Requests\Pharmacy\UploadAlphaBetaZipFileRequest;
use CloudMed\Jobs\Pharmacy\UpdateMedicamentsJob;
use Facades\CloudMed\Services\Pharmacy\MedicamentsUpdateService;
use Facades\CloudMed\Services\Pharmacy\MedicamentsService;
use Illuminate\Http\Request;
use CloudMed\Http\Controllers\Controller;
use Yoeunes\Toastr\Facades\Toastr;

class MedicamentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('Pharmacy.Medicaments.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
       return MedicamentsService::edit($id);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    /**
     * @return mixed
     */
    public function dataTable()
    {
        return MedicamentsService::dataTable();
    }

    public function medicamentsUpdate()
    {
        return view('Pharmacy.Medicaments.medicamentsUpdate.update');
    }

    public function uploadAlphaBetaZipFile(UploadAlphaBetaZipFileRequest $request)
    {
        MedicamentsUpdateService::uploadAlphaBetaZipFile($request->file);

        Toastr::warning("Actualización en proceso.");

        return \Response::json("ok", 200);
    }

    public function medicamentUpdatesDataTable()
    {
        return MedicamentsService::medicamentUpdatesDataTable();
    }
}

resources/views/Pharmacy/Medicaments/create.blade.php
@extends('layouts.app')
@section('pageName')
    Crear Deposito
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">
                    <div class="panel-actions">
                        <a href="#" class="fa fa-caret-down"></a>
                        <a href="#" class="fa fa-times"></a>
                    </div>
                </header>
                <h3 class="panel-title"></h3>
                <div class="panel-body">
                    @include('layouts.errors')
                    {!! Form::open(['route' => 'deposits.store']) !!}
                        @include('Administration.Deposits.fields')
                    {!! Form::close() !!}
                </div>
            </section>
        </div>
    </div>
@endsection

resources/views/Pharmacy/Medicaments/dataTableActions.blade.php
@can('medicaments.edit')
    <a href="{{route('medicaments.edit', $id)}}" class="btn btn-sm btn-default"><i class="fa fa-pencil-alt"></i></a>
@endcan

resources/views/Pharmacy/Medicaments/edit.blade.php
@extends('layouts.app')
@section('pageName')
    Editar Medicamento
@endsection


@section('content')
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">
                    <div class="panel-actions">
                    </div>
                    <h3 class="panel-title"></h3>
                </header>
                <div class="panel-body">
                    @include('layouts.errors')
                    @include('Pharmacy.Medicaments.fields')
                </div>
            </section>
        </div>
    </div>
@endsection

resources/views/Pharmacy/Medicaments/fields.blade.php
<div class="form-group">
    {{ Form::label('label', 'Troquel', ['class' => 'col-md-3 control-label']) }}
    <div class="col-md-6">
        {{ Form::text('label', $medicament->label, ['class' => 'form-control', 'disabled']) }}
    </div>
</div>

<div class="form-group">
    {{ Form::label('barcode', 'Código de barras', ['class' => 'col-md-3 control-label']) }}
    <div class="col-md-6">
        {{ Form::text('barcode', $medicament->barcode, ['class' => 'form-control', 'disabled']) }}
    </div>
</div>

<div class="form-group">
    {{ Form::label('name', 'Medicamento', ['class' => 'col-md-3 control-label']) }}
    <div class="col-md-6">
        {{ Form::text('name', $medicament->name, ['class' => 'form-control', 'disabled']) }}
    </div>
</div>

<div class="form-group">
    {{ Form::label('presentation', 'Presentación', ['class' => 'col-md-3 control-label']) }}
    <div class="col-md-6">
        {{ Form::text('presentation', $medicament->presentation, ['class' => 'form-control', 'disabled']) }}
    </div>
</div>

<div class="form-group">
    {{ Form::label('laboratory_code', 'Laboratorio', ['class' => 'col-md-3 control-label']) }}
    <div class="col-md-6">
        {{ Form::select('laboratory_code', \CloudMed\Models\Pharmacy\PharmaceuticalLaboratory::all()->pluck('name','code'), isset($medicament->laboratory) ? $medicament->laboratory->code : null, ['class' => 'form-control chosen-select', 'disabled', 'placeholder' => '-']) }}
    </div>
</div>

<div class="form-group">
    {{ Form::label('medicament_drug_code', 'Droga', ['class' => 'col-md-3 control-label']) }}
    <div class="col-md-6">
        {{ Form::select('medicament_drug_code', \CloudMed\Models\Pharmacy\MedicamentDrug::all()->pluck('description','code'), isset($medicament->drug) ? $medicament->drug->code : null, ['class' => 'form-control chosen-select', 'disabled', 'placeholder' => '-']) }}
    </div>
</div>

<div class="form-group">
    {{ Form::label('medicament_administration_line_code', 'Vía de Administración', ['class' => 'col-md-3 control-label']) }}
    <div class="col-md-6">
        {{ Form::select('medicament_administration_line_code', \CloudMed\Models\Pharmacy\MedicamentAdministrationLine::all()->pluck('description','code'), isset($medicament->administrationLine) ? $medicament->administrationLine->code : null, ['class' => 'form-control chosen-select', 'disabled', 'placeholder' => '-']) }}
    </div>
</div>

<div class="form-group">
    {{ Form::label('medicament_category_id', 'Categoría', ['class' => 'col-md-3 control-label']) }}
    <div class="col-md-6">
        {{ Form::select('medicament_category_id', \CloudMed\Models\Pharmacy\MedicamentCategory::all()->pluck('description', 'id'), $medicament->medicament_category_id, ['class' => 'form-control chosen-select', 'disabled', 'placeholder' => '-']) }}
    </div>
</div>

<div class="form-group">
    {{ Form::label('medicament_pharmacological_action_code', 'Acción farmacológica', ['class' => 'col-md-3 control-label']) }}
    <div class="col-md-6">
        {{ Form::select('medicament_pharmacological_action_code', \CloudMed\Models\Pharmacy\MedicamentPharmacologicalAction::all()->pluck('description','code'), isset($medicament->pharmacologicalAction) ? $medicament->pharmacologicalAction->code : null, ['class' => 'form-control chosen-select', 'disabled', 'placeholder' => '-']) }}
    </div>
</div>

<div class="form-group">
    {{ Form::label('units', 'Unidades x blister', ['class' => 'col-md-3 control-label']) }}
    <div class="col-md-6">
        {{ Form::text('units', $medicament->units, ['class' => 'form-control', 'disabled']) }}
    </div>
</div>

<div class="form-group">
    {{ Form::label('cost_price', 'Precio de Costo:', ['class' => 'col-md-3 control-label', 'disabled']) }}
    <div class="col-md-6">
        {{ Form::text('cost_price', $medicament->cost_price, ['class' => 'form-control']) }}
    </div>
</div>

<div class="form-group">
    {{ Form::label('sell_price', 'Precio de Venta:', ['class' => 'col-md-3 control-label']) }}
    <div class="col-md-6">
        {{ Form::text('sell_price', $medicament->sell_price, ['class' => 'form-control', 'disabled']) }}
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            {!! Form::submit('Guardar', ['class' => 'btn btn-warning']) !!}
            <a href="{!! route('medicaments.index') !!}" class="btn btn-danger">Cancelar</a>
        </div>
    </div>
</div>

resources/views/Pharmacy/Medicaments/index.blade.php
@extends('layouts.app')
@section('pageName')
    Medicamentos
@endsection

@section('content')
    @include('layouts.partials.table', [
        'tableTitle' => view('layouts.partials.newRowButton', ['url' => '/Pharmacy/Medicaments/create']),
        'tableId' => 'pharmacyTable',
        'tableColumns' => ['Código de Barras', 'Nombre', 'Presentación', 'Droga', 'Laboratorio', 'Precio', '¿En stock?', 'Acciones'],
    ])
@endsection

@section('scripts')
    {{ Html::script('/assets/js/Pharmacy/index.js') }}
@endsection