routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['web', 'auth']], function() {

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/profile', 'Administration\UsersController@profile')->name('profile');
    Route::post('/profile', 'Administration\UsersController@updateProfile')->name('profile.update');
    Route::get('/profile/image', 'Administration\UsersController@profileImage');
    Route::post('/profile/image', 'Administration\UsersController@updateProfileImage')->name('profileImage.update');
    Route::get('/profile/signature', 'Administration\UsersController@signatureImage');
    Route::post('/profile/signature', 'Administration\UsersController@updateSignatureImage')->name('signatureImage.update');
    Route::get('/profile/getSignature', 'Administration\UsersController@getSignature');


    /**
     * Usuarios
     */
    Route::resource('administration/users', 'Administration\UsersController');
    Route::get('/datatable/administration/users', 'Administration\UsersController@dataTable');

    /**
     * Roles / Perfiles
     */
    Route::resource('administration/roles', 'Administration\RolesController');
    Route::get('/datatable/administration/roles', 'Administration\RolesController@dataTable');
    Route::get('/administration/roles/{RoleId}/setPermissions', 'Administration\RolesController@editPermissions')->name('roles.editPermissions');
    Route::post('/administration/roles/{RoleId}/setPermissions', 'Administration\RolesController@updatePermissions')->name('roles.updatePermissions');

    /**
     * Obras Sociales
     */
    Route::resource('administration/medicalInsurances', 'Administration\MedicalInsurances');
    Route::get('/datatable/administration/medicalInsurances', 'Administration\MedicalInsurances@dataTable');
    Route::get('/administration/medicalInsurance/writeNews/{medicalInsuranceId}', 'Administration\MedicalInsurances@writeNews');
    Route::post('/administration/medicalInsurance/storeNews/{medicalInsuranceId}', 'Administration\MedicalInsurances@storeNews');
    Route::post('/administration/medicalInsurance/{medicalInsuranceId}/restore', 'Administration\MedicalInsurances@restoreTrashed')->name('medicalInsurances.restore');

    /**
     * Gerenciadoras
     */
    Route::resource('administration/medicalInsurancesManagers', 'Administration\MedicalInsurancesManagers');
    Route::get('/datatable/administration/medicalInsurancesManagers', 'Administration\MedicalInsurancesManagers@dataTable');
    Route::post('/administration/medicalInsurancesManagers/{medicalInsuranceManagerId}/restore', 'Administration\MedicalInsurancesManagers@restoreTrashed')->name('medicalInsurancesManagers.restore');

    /**
     * Nomencladores
     */
    Route::resource('administration/nomenclators', 'Administration\Nomenclators');
    Route::post('/administration/nomenclators/{nomenclator}/restore', 'Administration\Nomenclators@restoreTrashed')->name('nomenclators.restore');
    Route::get('/datatable/administration/nomenclators', 'Administration\Nomenclators@dataTable');

    /**
     * Prácticas de Nomencladores
     */
    //LIST
    Route::get('/administration/nomenclatorPractices/{nomenclatorId}', 'Administration\NomenclatorPractices@practicesList');
    Route::get('/datatable/administration/nomenclatorPractices/{nomenclatorId}', 'Administration\NomenclatorPractices@dataTable');
    //CREATE
    Route::get('/administration/nomenclatorPractices/create/{nomenclatorId}', 'Administration\NomenclatorPractices@create')->name('nomenclatorPractice.create');
    Route::post('/administration/nomenclatorPractices/create/{nomenclatorId}', 'Administration\NomenclatorPractices@store')->name('nomenclatorPractice.store');
    //EDIT
    Route::get('/administration/nomenclatorPractice/edit/{nomenclatorPracticeId}', 'Administration\NomenclatorPractices@edit')->name('nomenclatorPractice.edit');
    Route::patch('/administration/nomenclatorPractices/edit/{nomenclatorPracticeId}', 'Administration\NomenclatorPractices@update')->name('nomenclatorPractice.update');
    //GET INFO
    Route::get('/administration/nomenclatorPractices/get/{nomenclatorPracticeId}', 'Administration\NomenclatorPractices@getInfoById');
    Route::get('/administration/nomenclatorPractices/getByCode/{nomenclatorPracticeCode}', 'Administration\NomenclatorPractices@getInfoByCode');


    /** Rutas Especialidades */

    Route::resource('administration/specialties', 'Administration\SpecialtiesController');
    Route::post('/administration/specialties/{specialties}/restore', 'Administration\SpecialtiesController@restoreTrashed')->name('specialties.restore');
    Route::get('/datatable/administration/specialties', 'Administration\SpecialtiesController@dataTable');

    /** Rutas Departamentos */

    Route::resource('administration/departments', 'Administration\DepartmentsController');
    Route::post('/administration/departments/{departments}/restore', 'Administration\DepartmentsController@restoreTrashed')->name('departments.restore');
    Route::get('/datatable/administration/departments', 'Administration\DepartmentsController@dataTable');

    /** Rutas Depositos */

    Route::resource('administration/deposits', 'Administration\DepositsController');
    Route::post('/administration/deposits/{deposits}/restore', 'Administration\DepositsController@restoreTrashed')->name('deposits.restore');
    Route::get('/datatable/administration/deposits', 'Administration\DepositsController@dataTable');


    /** Seguros de mala práxis */
    Route::resource('administration/medicalMalpracticeInsurances', 'Administration\MedicalMalpracticeInsurances');
    Route::get('/datatable/administration/medicalMalpracticeInsurances', 'Administration\MedicalMalpracticeInsurances@dataTable');

    /**Especialistas */

    Route::resource('administration/specialists', 'Administration\SpecialistsController');
    Route::get('/datatable/administration/specialists', 'Administration\SpecialistsController@dataTable');


    /**
     * Rangos de prácticas de nomencladores
     */
    Route::resource('administration/nomenclatorRanges', 'Administration\NomenclatorRanges');
    Route::get('/datatable/administration/nomenclatorRanges', 'Administration\NomenclatorRanges@dataTable');

    /**Grupos de Practicas de Nomencladores */

    Route::resource('administration/nomenclatorPracticesGroup', 'Administration\NomenclatorPracticesGroupController');
    Route::get('/datatable/administration/nomenclatorPracticesGroup', 'Administration\NomenclatorPracticesGroupController@dataTable');

    /**
     * Convenios con obras sociales
     */
    /*RESOURCE*/
    Route::resource('billingDepartment/medicalInsuranceAgreements', 'BillingDepartment\MedicalInsuranceAgreements');
    /*DataTable de convenios*/
    Route::get('/datatable/billingDepartment/medicalInsuranceAgreements', 'BillingDepartment\MedicalInsuranceAgreements@dataTable');
    /*Modal para importar archivo de excel con las practicas valorizadas*/
    Route::get('/modals/billingDepartment/practicesAgreementModal/{medicalInsuranceAgreementId}', 'BillingDepartment\MedicalInsuranceAgreements@practicesAgreementModal');
    /*POST para subir archivo de practicas valorizadas*/
    Route::post('/billingDepartment/uploadPracticesAgreement/{medicalInsuranceAgreementId}', 'BillingDepartment\MedicalInsuranceAgreements@uploadPracticesAgreement')->name('medicalInsuranceAgreement.uploadPractices');
    /*DataTable de practicas convenidas*/
    Route::get('/datatable/billingDepartment/medicalInsurancePracticesAgreement/{medicalInsuranceAgreementId}', 'BillingDepartment\MedicalInsuranceAgreements@practicesAgreementDataTable');
    /*Vista de practicas convenidas*/
    Route::get('/billingDepartment/practicesAgreement/{medicalInsuranceAgreementId}', 'BillingDepartment\MedicalInsuranceAgreements@practicesAgreement');

    /*Modal para agregar una pràctica al convenio manualmente*/
    Route::get('/modals/billingDepartment/addPracticeAgreementModal', 'BillingDepartment\MedicalInsuranceAgreements@addPracticeAgreementModal');
    Route::post('/billingDepartment/practicesAgreement/{medicalInsuranceAgreementId}', 'BillingDepartment\MedicalInsuranceAgreements@storePracticeAgreement');
    /*Eliminar una pràctica convenida*/
    Route::post('/billingDepartment/practicesAgreement/{medicalInsuranceAgreementId}/delete', 'BillingDepartment\MedicalInsuranceAgreements@deleteSinglePracticeAgreement');

    /**
     * Categorías de empleados
     */
    Route::resource('/humanResourcesDepartment/employeesCategories', 'HumanResourcesDepartment\EmployeesCategories');
    Route::get('/datatable/humanResourcesDepartment/employeesCategories', 'HumanResourcesDepartment\EmployeesCategories@dataTable');

    /**
     * Pacientes
     */
    Route::resource('administration/patients', 'Administration\PatientsController');
    Route::get('/datatable/administration/patients', 'Administration\PatientsController@dataTable');
    Route::get('/administration/patient/findByDocumentNumber/{documentTypeId}/{documentNumber}', 'Administration\PatientsController@findByDocumentNumber');
    Route::get('/administration/patient/patientMedicalInsurances/{documentTypeId}/{documentNumber}', 'Administration\PatientsController@getPatientMedicalInsurances');

    /**
     * Helpers
     **/
    //Ciudades
    Route::get('/helpers/cities/cityByProvinceId/{provinceId}', 'HelpersController@citiesByProvinceId');
    //Rendiciones abiertas

app/Models/Administration/City.php
<?php

namespace CloudMed\Models\Administration;

use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    public $table = 'cities';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'city_name',
        'postal_code',
        'province_id'
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'city_name' => 'string',
        'postal_code' => 'string',
        'province_id' => 'integer',
    ];

    public function province()
    {
        return $this->belongsTo(Province::class, 'province_id');
    }
}

app/Models/Administration/Deposit.php
<?php

namespace CloudMed\Models\Administration;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Wildside\Userstamps\Userstamps;

class Deposit extends Model
{
    use Userstamps;
    use SoftDeletes;

    public $table = 'medication_deposits';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'name' => 'string'
    ];


    public static $rules = [
        'name' => 'required|unique:medication_deposits,name',
    ];

    public static $messages = [
        'name.required' => 'El campo Nombre es obligatorio.',
        'name.unique' => 'El nombre del deposito ya existe en la base de datos. Verifique que no esté suspendida.',
    ];
}

app/Http/Controllers/Administration/DepartmentsController.php
<?php

namespace CloudMed\Http\Controllers\Administration;

use CloudMed\Http\Requests\Administration\Departments\StoreDepartmentRequest;
use CloudMed\Http\Requests\Administration\Departments\UpdateDepartmentRequest;
use Facades\CloudMed\Services\Administration\DepartmentsService;

use Illuminate\Http\Request;
use CloudMed\Http\Controllers\Controller;


class DepartmentsController extends Controller
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        return view('Administration.Departments.index');
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('Administration.Departments.create');
    }

    /**
     * @param StoreDepartmentRequest $request
     * @return mixed
     */
    public function store(StoreDepartmentRequest $request)
    {
        return DepartmentsService::store($request);
    }

    /**
     * @param $DepartmentId
     * @return mixed
     */
    public function edit($DepartmentId)
    {
        $DepartmentId = $DepartmentId;
        return DepartmentsService::edit($DepartmentId);
    }

    /**
     * @param $DepartmentId
     * @param UpdateDepartmentRequest $request
     * @return mixed
     */
    public function update($DepartmentId, UpdateDepartmentRequest $request)
    {
        return DepartmentsService::update($DepartmentId, $request);
    }

    /**
     * @param $DepartmentId
     * @return mixed
     */
    public function destroy($DepartmentId)
    {
        return DepartmentsService::destroy($DepartmentId);
    }

    /**
     * @return mixed
     */
    public function dataTable()
    {
        return DepartmentsService::dataTable();
    }
}

app/Http/Controllers/Administration/DepositsController.php
<?php

namespace CloudMed\Http\Controllers\Administration;


use CloudMed\Http\Requests\Administration\Deposits\UpdateDepositRequest;
use CloudMed\Http\Requests\Administration\Deposits\StoreDepositRequest;
use Facades\CloudMed\Services\Administration\DepositsService;

use Illuminate\Http\Request;
use CloudMed\Http\Controllers\Controller;


class DepositsController extends Controller
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        return view('Administration.Deposits.index');
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('Administration.Deposits.create');
    }

    /**
     * @param StoreDepositRequest $request
     * @return mixed
     */
    public function store(StoreDepositRequest $request)
    {
        return DepositsService::store($request);
    }

    /**
     * @param $DepositId
     * @return mixed
     */
    public function edit($DepositId)
    {
        $DepositId = $DepositId;
        return DepositsService::edit($DepositId);
    }

    /**
     * @param $DepositId
     * @param UpdateDepositRequest $request
     * @return mixed
     */
    public function update($DepositId, UpdateDepositRequest $request)
    {
        return DepositsService::update($DepositId, $request);
    }

    /**
     * @param $DepositId
     * @return mixed
     */
    public function destroy($DepositId)
    {
        return DepositsService::destroy($DepositId);
    }

    /**
     * @return mixed
     */
    public function dataTable()
    {
        return DepositsService::dataTable();
    }
}

app/Http/Controllers/Administration/MedicalInsurances.php
<?php

namespace CloudMed\Http\Controllers\Administration;

use CloudMed\Http\Requests\Administration\MedicalInsurances\RestoreMedicalInsuranceTrashedRequest;
use CloudMed\Http\Requests\Administration\MedicalInsurances\StoreMedicalInsuranceRequest;
use CloudMed\Http\Requests\Administration\MedicalInsurances\StoreMedicalInsurancesNewsBoardRequest;
use CloudMed\Http\Requests\Administration\MedicalInsurances\UpdateMedicalInsuranceRequest;
use Facades\CloudMed\Services\Administration\MedicalInsurancesService;
use CloudMed\Http\Controllers\Controller;

class MedicalInsurances extends Controller
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        return view('Administration.MedicalInsurances.index');
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('Administration.MedicalInsurances.create');
    }

    /**
     * @param StoreMedicalInsuranceRequest $request
     * @return mixed
     */
    public function store(StoreMedicalInsuranceRequest $request)
    {
        return MedicalInsurancesService::store($request);
    }

    /**
     * @param $medicalInsuranceId
     * @return mixed
     */
    public function edit($medicalInsuranceId)
    {
        return MedicalInsurancesService::edit($medicalInsuranceId);
    }

    /**
     * @param $medicalInsuranceId
     * @param UpdateMedicalInsuranceRequest $request
     * @return mixed
     */
    public function update($medicalInsuranceId, UpdateMedicalInsuranceRequest $request)
    {
        return MedicalInsurancesService::update($medicalInsuranceId, $request);
    }

    /**
     * @param $medicalInsuranceId
     * @return mixed
     */
    public function destroy($medicalInsuranceId)
    {
        return MedicalInsurancesService::destroy($medicalInsuranceId);
    }

    /**
     * @return mixed
     */
    public function dataTable()
    {
        return MedicalInsurancesService::dataTable();
    }

    /**
     * @param $medicalInsuranceId
     * @param RestoreMedicalInsuranceTrashedRequest $request
     * @return mixed
     */
    function restoreTrashed($medicalInsuranceId, RestoreMedicalInsuranceTrashedRequest $request)
    {
        return MedicalInsurancesService::restoreTrashed($medicalInsuranceId);
    }

    public function writeNews($medicalInsuranceId)
    {
        return MedicalInsurancesService::writeNews($medicalInsuranceId);
    }

    public function storeNews($medicalInsuranceId, StoreMedicalInsurancesNewsBoardRequest $request)
    {
        return MedicalInsurancesService::storeNews($medicalInsuranceId, $request);
    }
}

resources/views/Administration/Nomenclators/create.blade.php
@extends('layouts.app')
@section('pageName')
    Crear Nomenclador
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">
                    <div class="panel-actions">
                        <a href="#" class="fa fa-caret-down"></a>
                        <a href="#" class="fa fa-times"></a>
                    </div>
                </header>
                <h3 class="panel-title"></h3>
                <div class="panel-body">
                    @include('layouts.errors')
                    {!! Form::open(['route' => 'nomenclators.store']) !!}
                        @include('Administration.Nomenclators.fields')
                    {!! Form::close() !!}
                </div>
            </section>
        </div>
    </div>
@endsection

@section('scripts')
    {!! Html::script('/assets/js/administration/Nomenclators/create.js') !!}
@endsection

resources/views/Administration/Nomenclators/dataTableActions.blade.php
<div class="form-inline">
    @can('medicalInsurances.edit')
        <a title="Modificar nomenclador" href="{{route('nomenclators.edit', $row->id)}}" class="btn btn-sm btn-warning"><i class="fa fa-edit"></i></a>
    @endcan

    @if(is_null($row->deleted_at))
        @can('nomenclators.delete')
            {!! Form::open(['id' => $row->id, 'route' => ['nomenclators.destroy', $row->id], 'method' => 'delete', 'style' => 'display: inline;']) !!}
            {!! Form::button('<i class="fa fa-check"></i>', [
                    'class' => 'btn btn-sm btn-success',
                    'onclick' => "return confirmSubmit(".$row->id.",'¿Está seguro que desea suspender el nomenclador?'); return false;",
                    'title' => 'Suspender Nomenclador'
            ]) !!}
            {!! Form::close() !!}
        @endcan
    @else
        {!! Form::open(['id' => $row->id, 'route' => ['nomenclators.restore', $row->id], 'method' => 'post', 'style' => 'display: inline;']) !!}
        {!! Form::button('<i class="fa fa-times"></i>', [
                    'class' => 'btn btn-sm btn-danger',
                    'onclick' => "confirmSubmit($row->id, '¿Está seguro de que desea habilitar el nomenclador?'); return false;",
                    'title' => 'Habilitar Nomenclador'
            ]) !!}
        {!! Form::close() !!}
    @endif
</div>

resources/views/Administration/Nomenclators/edit.blade.php
@extends('layouts.app')
@section('pageName')
    Editar Nomenclador
@endsection


@section('content')
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">
                    <div class="panel-actions">
                        <a href="#" class="fa fa-caret-down"></a>
                        <a href="#" class="fa fa-times"></a>
                    </div>
                </header>
                <h3 class="panel-title"></h3>
                <div class="panel-body">
                    @include('layouts.errors')
                    {!! Form::model($nomenclator, ['route' => ['nomenclators.update', $nomenclator->id], 'method' => 'patch']) !!}
                        @include('Administration.Nomenclators.fields')
                    {!! Form::close() !!}
                </div>
            </section>
        </div>
    </div>
@endsection

@section('scripts')
    {!! Html::script('/assets/js/administration/Nomenclators/edit.js') !!}
@endsection

resources/views/Administration/Nomenclators/fields.blade.php
<div class="form-group">
    {{ Form::label('name', 'Nombre:', ['class' => 'col-md-3 control-label']) }}
    <div class="col-md-6">
        {{ Form::text('name', null, ['class' => 'form-control']) }}
    </div>
</div>

@if(!isset($nomenclator))
    <div class="form-group">
        {{ Form::label('nomenclatorMirror', 'Copiar prácticas de:', ['class' => 'col-md-3 control-label']) }}
        <div class="col-md-6">
            {{ Form::select('nomenclatorMirror', \CloudMed\Models\Administration\Nomenclators\Nomenclator::all()->pluck('name', 'id'), null, ['class' => 'form-control chosen-select', 'placeholder' => 'No copiar prácticas']) }}
        </div>
    </div>
@endif

<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            {!! Form::submit('Guardar', ['class' => 'btn btn-warning']) !!}
            <a href="{!! route('nomenclators.index') !!}" class="btn btn-danger">Cancelar</a>
        </div>
    </div>
</div>

resources/views/Administration/Nomenclators/index.blade.php
@extends('layouts.app')
@section('pageName')
    Nomencladores
@endsection

@section('content')
    @include('layouts.partials.table', [
        'tableTitle' => view('layouts.partials.newRowButton', ['url' => '/administration/nomenclators/create']),
        'tableId' => 'nomenclatorsTable',
        'tableColumns' => ['Nombre', 'Estado', 'Prácticas', 'Acciones'],
    ])
@endsection
@section('scripts')
    {{ Html::script('/assets/js/administration/Nomenclators/index.js') }}
@endsection

resources/views/Administration/Nomenclators/practicesListDataTableButton.blade.php
<a href="/administration/nomenclatorPractices/{{$row->id}}" class="btn btn-sm btn-warning" title="Listado de prácticas del nomenclador"><i class="fa fa-pencil-alt"></i></a>